version: "3"
services:
  app:
    build:
      context: .
    environment:
      DB_HOST: db
    ports:
      - "${DB_PORT:-3000}:3000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD:-123}"
      POSTGRES_DB: "${DB_DATABASE:-postgres}"
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 10s
      retries: 0

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "${ADMINER_PORT:-81}:8080"
