version: "3"
services:
  db:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD:-123}"
      POSTGRES_DB: "${DB_DATABASE:-postgres}"
    ports:
      - "${DB_PORT:-5432}:5432"

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "${ADMINER_PORT:-81}:8080"
